Testing the script

diff --git a/.github/workflows/samples.yml b/.github/workflows/samples.yml
--- a/.github/workflows/samples.yml
+++ b/.github/workflows/samples.yml
@@ -79,12 +79,14 @@ jobs:
       - name: Change token rotation to 30s
         if: ${{ matrix.sample-executable.name == 'kvsVideoOnlyRealtimeStreamingSample-token-rotation' }}
         run: |
+          set -x
           file_path="./dependency/libkvspic/kvspic-src/src/client/src/StreamEvent.c"
           string_to_replace='pKinesisVideoStream->streamingAuthInfo.expiration = MIN(expiration, currentTime + MAX_STREAMING_TOKEN_EXPIRATION_DURATION);'
           string_to_replace_with='pKinesisVideoStream->streamingAuthInfo.expiration = MIN(expiration, currentTime + MIN_STREAMING_TOKEN_EXPIRATION_DURATION);'
         
+          set +e
           echo "Checking if the pattern exists before replacement:"
-          occurrences=$(grep -F -c "$string_to_replace" "$file_path")
+          export occurrences=$(grep -F -c "$string_to_replace" "$file_path")
           if [[ "$occurrences" -gt 1 ]]; then
             echo "There is more than 1 of: \`$string_to_replace\` in \`$file_path\`!"
             exit 1
@@ -93,6 +95,7 @@ jobs:
             exit 1
           fi
           echo "Yes"
+          set -e
         
           # Replace the line, while preserving the indentation
           awk -v old="$string_to_replace" -v new="$string_to_replace_with" \
@@ -106,7 +109,7 @@ jobs:
           mv temp_file "$file_path"
 
           echo "Checking if the replacement was successful:"
-          grep -F "$string_to_replace_with" "$file_path" || (echo "Replacement failed" && exit 1)
+          grep -F -c "$string_to_replace_with" "$file_path" || (echo "Replacement failed" && exit 1)
           echo "Yes"
         
           cd "$GITHUB_WORKSPACE/build"
